### ISSUE TITLE
请问一下什么时候开源代码呢？用的什么框架呢？pytorch吗？

### ISSUE THREAD

**Issue by gittigxuy** [qijiezhao/CFENet#1]

**Comment by qijiezhao** [comment]
In two months. Actually, we will firstly release code of [M2Det](https://github.com/qijiezhao/M2Det) in 20 days, and then release the code of CFENet.

**Comment by gittigxuy** [comment]
M2Det这个测评是根据voc2007进行测评的吗？

**Comment by qijiezhao** [comment]
mscoco Qijie Zhao Visual Data Interpreting and Generation,  Institute of Computer Science & Technology (VDIG.ICST) Peking University 在2018年09月25日 12:28，xuy 写道： M2Det这个测评是根据voc2007进行测评的吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by overfitover** [comment]
我就喜欢用中文交流，让英语母语的自个儿倒腾去吧！哈哈哈， 期待中。。。

**Comment by nationalflag** [comment]
你的这两个项目等的好捉急啊，哈哈

**Comment by qijiezhao** [comment]
@nationalflag We have released the unstable version:
https://github.com/qijiezhao/CFENet/tree/working
you can try to train it on COCO or VOC.

**Comment by qijiezhao** [comment]
***@***.******@***.***今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码

**Comment by qijiezhao** [comment]
2022年个人劳动补贴，请及时查看附件，务必当天填写申报！

**Comment by qijiezhao** [comment]
foxmail.com 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-20/10:37:06(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      foxmail.com   安全检测系统    
       2023-03-20/10:37:06(CET)





 
 



______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by qijiezhao** [comment]
sensetime.com 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-27/10:13:07(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      sensetime.com   安全检测系统    
       2023-03-27/10:13:07(CET)

**Comment by qijiezhao** [comment]
reply.github.com 帐户
       登录活动异常 已检测到最近登录到 ***@***.*** 的一些异常。
      
        
        
          登录详细信息
        
          国家/地区: 
            波兰(华沙) 
        
          IP 
            地址: 91.208.250.24
      
      
        
        
          日期: 
            2023-03-27/13:15:26(CET)
        
          平台: 
            Windows
        
          浏览器: 
            Chrome
        
          请点击验证当前密码按钮保持确保账户正常使用，让我们确定这是你本人。如果不是，系统会暂停您的帐户

  
  
    
      验证当前密码
      reply.github.com   安全检测系统    
       2023-03-27/13:15:26(CET)
