### ISSUE TITLE
when I run test.py,I get following error

### ISSUE THREAD

**Issue by gittigxuy** [qijiezhao/CFENet#10]
AttributeError: 'ConfigDict' object has no attribute 'cuda'

I think you could add 

test_cfg = dict(
    topk = 0,
    iou_jaccard = 0.45,
    soft_nms = True,
    score_threshold = 0.1,
    save_folder = 'eval'
    )

cuda=True
in the cfenet512_vgg16.py

**Comment by gittigxuy** [comment]
how to test own dataset with coco / voc dataset

**Comment by qijiezhao** [comment]
Thank you, I have fixed it.
Else, if you met any other BUGs later, you can directly PULL REQUEST, thank you.
