### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by LightToYang** [qijiezhao/CFENet#18]
Environment:
Linux 16.04
python 3.7
cuda 9.2
pytorch 0.4.1

When I compile the nms and coco tools, by using ./make.sh I got this kind of error
```
nms/cpu_nms.c:8966:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’ tstate->exc_traceback = local_tb;  
error: command 'gcc' failed with exit status 1
```

**Comment by Karthik-Suresh93** [comment]
Downgrade python 3.7 to python 3.6 and recompile. It is some issue related with cython compatibility with Python 3.7

**Comment by LightToYang** [comment]
Thank you, you are right. It works fine now.
