### ISSUE TITLE
how about demo.py?when will you release this code?

### ISSUE THREAD

**Issue by gittigxuy** [qijiezhao/CFENet#3]

**Comment by qijiezhao** [comment]
Ideally, the refactored code should achieve AP of 39+ and 43+ on MS-COCO by using single-scale and multi-scale inference strategy(CFE512, SEResNet50). 
But it will take time for me to retrain the models:
now, it's about 4 days left to prepare the pre-trained CFENet512-VGG and CFENet300-SEResNet50. and the CFENet512-SEResNet50 will cost a week more.
CFENet800-VGG is optional(time, time, time...), but I will prepare a code for training, and find volunteers for this.
When the strongest model has been accomplished, then release the demo.py.
