### ISSUE TITLE
对于cfenet.py文件有点问题

### ISSUE THREAD

**Issue by gittigxuy** [qijiezhao/CFENet#5]
问题1：
请问一下为什么要将输入数据x，拆分成t1和t2，这两个变量对应论文中图3（a）的哪个部分呢？
问题2：
在_prepare_arterial（），对于该函数当中，你应该是在backbone之后的每一层之间都添加了cfe model吧？是这样的吗？
问题3：
seresnet50怎么仅仅是t0, t1 = self.base(x)，而没有像vgg那样做了层的情况判断？
谢谢了

**Comment by qijiezhao** [comment]
这个working的branch版本不对应论文中的方法，而是一个参数量更少，效果却更好的方法；
之后会有一个和论文中对应的branch/.py；
seresnet50你可以看看senet.py里的写法；
另外，你现在训的怎么样了，有没有复现出我表里的结果？还有就是 我想知道一下这份代码有没有其他bug？

**Comment by gittigxuy** [comment]
我并没有训练coco/voc数据集，而是训练自己的数据集，所以感谢你的开源，希望你尽快放出demo.py文件

**Comment by gittigxuy** [comment]
跑通了




| |
xuy
邮箱：18969043167@163.com
|

Signature is customized by Netease Mail Master

在2018年11月02日 11:23，QijieZhao 写道：

@gittigxuy 那训你自己的数据集是否成功训练了呢？
