### ISSUE TITLE
Why use 1×k and a k×1 conv in one branch while k×1 and  1×k conv in the others on CFE module

### ISSUE THREAD

**Issue by chunyanlian** [qijiezhao/CFENet#6]
hello,QijieZhao.  I have noticed that you use 1×k and a k×1 conv in one branch while k×1 and  1×k conv in the others on CFE module. Can you tell me why you disign the module like this? What's  will be if two branch use the same conv? Can you tell me some reason in theory? I have not find the explanations in the paper. thank you very much.

**Comment by qijiezhao** [comment]
Our full paper has explained the motivation, refer to the design of large separable convolution in Light-head and Large kernel matters paper.
In theory, 1xk kernels with two inverted ordering of directions can learn more patterns than the ones only doubled in the same direction. For instance, imagine a scene: a person stands in front of a car, two inverted ordering of directions can contribute more to localize and recognize them both.

**Comment by chunyanlian** [comment]
Thank you for your quick reply. I will read Large kenel mattters for more dedtails.
